// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyComlaQI6OYztqPV9hZYMWeLUP2R9MK-tM',
    appId: '1:1072332288802:web:90de67494d5949524feb7b',
    messagingSenderId: '1072332288802',
    projectId: 'recipe-app-41e7f',
    authDomain: 'recipe-app-41e7f.firebaseapp.com',
    storageBucket: 'recipe-app-41e7f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKcLRy29WUyHHBeySK7u-RHTab7HCSvs0',
    appId: '1:1072332288802:android:7812b999853820984feb7b',
    messagingSenderId: '1072332288802',
    projectId: 'recipe-app-41e7f',
    storageBucket: 'recipe-app-41e7f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmyHKkVVB-6c269vN80TdcH0YpjiZm3gI',
    appId: '1:1072332288802:ios:bd2b57a1e5e17e874feb7b',
    messagingSenderId: '1072332288802',
    projectId: 'recipe-app-41e7f',
    storageBucket: 'recipe-app-41e7f.firebasestorage.app',
    iosBundleId: 'com.example.mealdbApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmyHKkVVB-6c269vN80TdcH0YpjiZm3gI',
    appId: '1:1072332288802:ios:bd2b57a1e5e17e874feb7b',
    messagingSenderId: '1072332288802',
    projectId: 'recipe-app-41e7f',
    storageBucket: 'recipe-app-41e7f.firebasestorage.app',
    iosBundleId: 'com.example.mealdbApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyComlaQI6OYztqPV9hZYMWeLUP2R9MK-tM',
    appId: '1:1072332288802:web:62c824a0dd4e8cde4feb7b',
    messagingSenderId: '1072332288802',
    projectId: 'recipe-app-41e7f',
    authDomain: 'recipe-app-41e7f.firebaseapp.com',
    storageBucket: 'recipe-app-41e7f.firebasestorage.app',
  );
}
